# See: https://dart.dev/tools/pub/pubspec
name: conreality_beacon_example
description: Demonstrates how to use the conreality_beacon plugin.
publish_to: none

environment:
  sdk: ">=2.4.0 <3.0.0"
  flutter: ">=1.7.8 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  conreality_beacon:
    path: ../

flutter:
  uses-material-design: true
