# See: https://dart.dev/tools/pub/pubspec
name: conreality_headset
version: 0.1.4
description: >-
  Headset audio and text-to-speech support for Conreality live-action games.
author: Conreality Team <conreality@googlegroups.com>
homepage: https://github.com/conreality/conreality-plugins/tree/master/conreality_headset

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.5.4-hotfix.2 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: app.conreality.plugins.headset
    pluginClass: ConrealityHeadsetPlugin
