# See: https://dart.dev/tools/pub/pubspec
name: conreality_scripts
version: 1.0.0+20190704.1
description: >-
  Precompiled scripts repository for Conreality live-action games.
author: Conreality Team <conreality@googlegroups.com>
homepage: https://github.com/conreality/conreality-plugins/tree/master/conreality_scripts

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.5.4-hotfix.2 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - scripts/VERSION
    - scripts/console/
    - scripts/developer/
    - scripts/player/
